events {
    worker_connections 1024;
}

stream {
    upstream nginx_l7 {
        server nginx-l7-1:80;
        server nginx-l7-2:80;
    }

    server {
        listen 80;
        proxy_pass nginx_l7;
    }
}